In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,4])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 4]


In [4]:
from numpy import array

arr2 = array([1,2,4,5])
print(arr2)

[1 2 4 5]


In [2]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [3]:
c = np.array([[1,2,3],[4,5,6]])
print(c.size)

6


In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6 7 8]


In [8]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0, 1])

2


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


### Class 15 Numpy continue

In [5]:
arr3 = np.array([[23, 234, 234, 234], [1, 3,5 ,6 ]])

print(arr3[0,1])
arr3T = arr3.T
print(arr3T[0,1])
np.dot(arr3, arr3T)

arr3.dot(arr3T)

234
1


array([[164797,   3299],
       [  3299,     71]])

In [6]:
print(arr3.ndim)
print(arr2.ndim)

2
1


In [8]:
arr4 = np.array([[1,5], [4,8]])
print(arr4)

[[1 5]
 [4 8]]


In [12]:
arr5 = np.ones((2, 3, 7))
print(arr5)

arr6 = np.zeros((2, 3, 7))
print(arr6)


arr7 = np.random.normal((2, 3, 7))
print(arr7)

[[[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]]
[[[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]]
[1.96113716 2.37439468 6.97204015]


In [13]:
arr3d = np.random.random((2,3,5))
print(arr3d.ndim)
print(arr3d.shape)
print(arr3d.size)
arr3d

3
(2, 3, 5)
30


array([[[0.60880528, 0.65362481, 0.97350127, 0.19143223, 0.22899657],
        [0.29549562, 0.22570652, 0.58549267, 0.68298819, 0.43142345],
        [0.78174513, 0.47344909, 0.09002881, 0.77587305, 0.88491915]],

       [[0.72468023, 0.66929085, 0.0140326 , 0.41686563, 0.39308361],
        [0.65203456, 0.46192679, 0.11329841, 0.21798222, 0.78150174],
        [0.28495226, 0.84141801, 0.21895488, 0.29930463, 0.39365279]]])

In [17]:
arr3dr = arr3d.reshape(-1)
print(arr3dr.ndim)
arr3drr = arr3d.reshape(5,6)
print(arr3drr)

1
[[0.60880528 0.65362481 0.97350127 0.19143223 0.22899657 0.29549562]
 [0.22570652 0.58549267 0.68298819 0.43142345 0.78174513 0.47344909]
 [0.09002881 0.77587305 0.88491915 0.72468023 0.66929085 0.0140326 ]
 [0.41686563 0.39308361 0.65203456 0.46192679 0.11329841 0.21798222]
 [0.78150174 0.28495226 0.84141801 0.21895488 0.29930463 0.39365279]]


In [30]:
arr8 = np.array([[1,2,3,4], [5,6,7,8]])
print(arr8)
print(arr8[0,-2])

arr9 = np.array([1,2,3,4,5,6,7,8])
print(arr9[1:5:2])
print(arr9[-3:-1])

print(arr8[1,1:4])

print(arr8[0:2, 2])

[[1 2 3 4]
 [5 6 7 8]]
3
[2 4]
[6 7]
[6 7 8]
[3 7]


In [10]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [31]:
# write a program to find sum and average of 10 numbers stored in numpy array.

nparray = np.array([1,2,3,4,5,6,7,8,9,10])
sumarr = nparray.sum()
print(sumarr)

55


In [43]:
# write a program to find sum of two matrices.

nparray1 = np.array([1,2,3,4,5,6,7,8,9,10])
nparray2 = np.array([1,2,3,4,5,6,7,8,9,10])

sumA = np.array([0,0,0,0,0,0,0,0,0,0], ndmin=1)
for (index, value) in enumerate(nparray1):
    sumB = nparray1[index]+nparray2[index]
    sumA[index] = sumB
print(sumA)

print(np.add(nparray1, nparray2))

[ 2  4  6  8 10 12 14 16 18 20]
[ 2  4  6  8 10 12 14 16 18 20]


In [16]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
for x in np.nditer(arr[0:2, 0::3]):
    print(x)

1
4
5
8
