In [2]:
import numpy as np;
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [4]:
c = np.array([[1,2,3],[4,5,6]])
print(c.size)
print(c.shape)

6
(2, 3)


In [8]:
# Reshape
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)
print(newarr.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [6]:
#Flattening
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6 7 8]


In [9]:
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [10]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0, 1])

2


In [11]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, -2])

9


In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:5])
print(arr[2:])
print(arr[:])

[1 2 3 4 5]
[3 4 5 6 7]
[1 2 3 4 5 6 7]


In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


In [16]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [17]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [18]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [3]:
a = np.array([1,2,3,4,5])
np.save('outfile',a)

In [4]:
b = np.load('outfile.npy')
print(b)

[1 2 3 4 5]


In [5]:
a = np.array([1,2,3,4,5])
np.savetxt('out.txt',a)
b = np.loadtxt('out.txt')
print(b)

[1. 2. 3. 4. 5.]


In [6]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [11]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

x[0] = 78

print(x)
print(arr)

[42  2  3  4  5]
[42  2  3  4  5]
[78  2  3  4  5]
[78  2  3  4  5]


In [8]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [12]:
arr = np.arange(0,10,.5,float)
print(arr)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [16]:
arr = np.linspace(0, 10, 5, True, True, np.single)
print(arr)

(array([ 0. ,  2.5,  5. ,  7.5, 10. ], dtype=float32), 2.5)


2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
